// <auto-generated />
using System;
using Lumen.Modules.FocusStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.FocusStats.Data.Migrations
{
    [DbContext(typeof(FocusStatsContext))]
    [Migration("20241226191628_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("focusstats")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.FocusStats.Common.UserFocusedActivity", b =>
                {
                    b.Property<string>("ProgramExe")
                        .HasColumnType("character varying");

                    b.Property<string>("ProgramName")
                        .HasColumnType("character varying");

                    b.Property<int>("SecondsDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProgramExe", "ProgramName");

                    b.ToTable("Activities", "focusstats");
                });
#pragma warning restore 612, 618
        }
    }
}
