// <auto-generated />
using System;
using System.Collections.Generic;
using Lumen.Modules.FocusStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.FocusStats.Data.Migrations
{
    [DbContext(typeof(FocusStatsContext))]
    partial class FocusStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("focusstats")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.FocusStats.Common.Rules.CleaningRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Tests")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("Regex")
                        .IsUnique();

                    b.ToTable("CleaningRules", "focusstats");
                });

            modelBuilder.Entity("Lumen.Modules.FocusStats.Common.Rules.TaggingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("character varying[]");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Tests")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("Regex")
                        .IsUnique();

                    b.ToTable("TaggingRules", "focusstats");
                });

            modelBuilder.Entity("Lumen.Modules.FocusStats.Common.UserFocusedActivity", b =>
                {
                    b.Property<string>("Device")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppOrExe")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<int>("SecondsDuration")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("character varying[]");

                    b.HasKey("Device", "StartTime");

                    b.HasIndex("StartTime", "SecondsDuration", "AppOrExe", "Name", "Device");

                    b.ToTable("Activities", "focusstats");
                });
#pragma warning restore 612, 618
        }
    }
}
